functional:
    -Пользователь должен иметь возможность искать товары по ключевому слову или категории.
    -Пользователь должен иметь возможность фильтровать товары
    -Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
    -Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
    -Пользователь может просматривать каталог товаров, пользуясь постраничным выводом.
    -На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
    -Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
    -На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
non-functional:
    -Сайт должен быть безопасным и защищать данные пользователя.
    -Сайт должен быть протестирован на совместимость с последними версиями браузеров.
    -Сайт должен быть способен обрабатывать большое количество трафика.
    -Сайт должен быть доступен на различных устройствах.
    -Корзина хранится в сессии браузера.
    -Сайт должен иметь мобильную версию.
    -Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
    -Сайт должен быть SPA приложение, которое не перезагружает страницу
implicit:
    -Пользователь должен иметь возможность создавать и входить в личный кабинет (зарегистрироваться на сайте, авторизоваться)
    -После авторизации, пользователя должно перенаправлять на гланвую страницу магазина
    -Сайт должен использовать куки
    -Сайт должен быть локализован под разные языки
    -Сайт должен иметь возможность добавлять товары в Избранное.
    -Сайт должен спрашивать у пользователя сохранять данные о карте для последующих покупок или нет.
    -При просмотре информации о товаре, пользователь должен иметь возможность вернуться в каталог на ту страницу, на которой был найден данный товар.
    -При просмотре информации о товаре, товар должен содержать характеристики (Размеры, материал)
    -Сайт должен содержать Каталог товаров с товарами, разделенными по категориям (Смартфоны, часы, парфюм, MacBook etc.)
    -Сайт должен иметь возможность при заказе товара указать способ получения (курьер или самовывоз), удобный способ связи с клиентом, удобную дату получения заказа
    -Сайт должен иметь раздел Заказы
    -Сайт должен иметь раздел Акции
    -При просмотре товара указывать, что товар в наличие
    -При просмотре товара, у товара должно быть краткое описание
    -Сайт должен запрашивать у пользователя определять геоданные, отсюда будет меняться язык сайта для удобства пользователя, цены